name: surabaya
description: "A new Flutter project."
publish_to: "none"
version: 2.2.0+3

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1
  get: ^4.6.6
  go_router: ^14.4.1
  grouped_list: ^6.0.0
  html: ^0.15.6
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  page_transition: ^2.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
